# Generated by Django 5.2 on 2025-06-05 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recrutement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='recrutement.quizquestion'),
        ),
        migrations.AddField(
            model_name='recours',
            name='candidature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recours', to='recrutement.candidature'),
        ),
        migrations.AddField(
            model_name='recours',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recours_traites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoursactionhistory',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoursactionhistory',
            name='recours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='recrutement.recours'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='recrutement.trainingmodule'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='candidature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='recrutement.candidature'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='evaluateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements_effectues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('user', 'question')},
        ),
    ]
