# Generated by Django 5.2 on 2025-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0003_alter_candidature_candidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('envoye', 'Envoyée'), ('en_traitement', 'En cours de traitement'), ('valide', 'Validée'), ('rejete', 'Rejetée'), ('recours', 'Recours')], default='envoye', max_length=20),
        ),
    ]
