# Generated by Django 5.2 on 2025-06-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0004_alter_candidature_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='decision',
            field=models.CharField(choices=[('ok', 'Retenue'), ('ko', 'Rejetée')], default='ko', max_length=20),
        ),
    ]
