# Generated by Django 5.2 on 2025-06-14 19:17

import recrutement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0005_candidature_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='aptitude_physique',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=recrutement.models.Candidature.candidature_upload_path),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=recrutement.models.Candidature.candidature_upload_path),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='diplome',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=recrutement.models.Candidature.candidature_upload_path),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='lettre_motivation',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=recrutement.models.Candidature.candidature_upload_path),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='piece_identite',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=recrutement.models.Candidature.candidature_upload_path),
        ),
    ]
