# Generated by Django 5.2 on 2025-06-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0006_alter_candidature_aptitude_physique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='decision',
        ),
        migrations.AddField(
            model_name='traitement',
            name='decision',
            field=models.CharField(choices=[('ok', 'Retenue'), ('ko', 'Rejetée')], default='ko', max_length=20),
        ),
    ]
