# Generated by Django 5.2 on 2025-06-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0007_remove_candidature_decision_traitement_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='decision',
            field=models.CharField(choices=[('ok', 'Retenue'), ('ko', 'Rejetée')], default='ko', max_length=2),
        ),
    ]
