# Generated by Django 5.2 on 2025-06-06 14:40

import datetime
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profilcandidat_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='date_de_naissance',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 6, 14, 40, 23, 279167, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='photo',
            field=models.FileField(blank=True, default='<function ProfilCandidat.user_photo_path at 0x000002041243C7C0>/default.jpg', null=True, upload_to=users.models.ProfilCandidat.user_photo_path),
        ),
    ]
