# Generated by Django 5.2 on 2025-06-07 00:32

import datetime
import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_evenement', models.CharField(max_length=50)),
                ('visible_pour', models.CharField(default='candidat', max_length=50)),
                ('lieu', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_participants', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('confirmé', 'Confirmé'), ('programmé', 'Programmé')], default='en attente', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('candidat', 'Futur élève'), ('eleve', 'Elève'), ('alumni', 'Ancien élève'), ('evaluateur', 'Evaluateur'), ('formateur', 'Formateur'), ('admin', 'Admin')], default='candidat', max_length=25),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='date_de_naissance',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 7, 0, 32, 55, 317107, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='photo',
            field=models.FileField(blank=True, default='<function ProfilCandidat.user_photo_path at 0x0000028B8F2CC7C0>/default.jpg', null=True, upload_to=users.models.ProfilCandidat.user_photo_path),
        ),
        migrations.CreateModel(
            name='RolePromotionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_role', models.CharField(choices=[('eleve', 'Elève'), ('alumni', 'Ancien élève'), ('evaluateur', 'Evaluateur'), ('formateur', 'Formateur'), ('admin', 'Admin')], default='eleve', max_length=25)),
                ('justification', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de promotion de rôle',
                'verbose_name_plural': 'Demandes de promotion de rôle',
            },
        ),
    ]
