# Generated by Django 5.2 on 2025-06-09 18:20

import datetime
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_notification_user_notification_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='date_de_naissance',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 9, 18, 20, 57, 851716, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='photo',
            field=models.FileField(blank=True, default='<function ProfilCandidat.user_photo_path at 0x000002B27700C860>/default.jpg', null=True, upload_to=users.models.ProfilCandidat.user_photo_path),
        ),
    ]
