# Generated by Django 5.2 on 2025-06-09 19:28

import datetime
import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profilcandidat_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilcandidat',
            name='date_de_naissance',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 9, 19, 28, 3, 917390, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='numero_piece_identite',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_numero_piece_identite', message="Ce champ n'accepte que des lettres et des chiffres.", regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='photo',
            field=models.FileField(blank=True, default='<function ProfilCandidat.user_photo_path at 0x0000021E32D3C7C0>/default.jpg', null=True, upload_to=users.models.ProfilCandidat.user_photo_path),
        ),
    ]
