# Generated by Django 5.2 on 2025-06-16 02:42

import datetime
import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profilcandidat_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilcandidat',
            name='date_de_naissance',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 16, 2, 42, 50, 980495, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='photo',
            field=models.FileField(blank=True, default='<function ProfilCandidat.user_photo_path at 0x000002B3B1C7C720>/default.jpg', max_length=255, null=True, upload_to=users.models.ProfilCandidat.user_photo_path),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='score_obtenu',
            field=models.FloatField(blank=True, choices=[(60, '60'), (61, '61'), (62, '62'), (63, '63'), (64, '64'), (65, '65'), (66, '66'), (67, '67'), (68, '68'), (69, '69'), (70, '70'), (71, '71'), (72, '72'), (73, '73'), (74, '74'), (75, '75'), (76, '76'), (77, '77'), (78, '78'), (79, '79'), (80, '80'), (81, '81'), (82, '82'), (83, '83'), (84, '84'), (85, '85'), (86, '86'), (87, '87'), (88, '88'), (89, '89'), (90, '90'), (91, '91'), (92, '92'), (93, '93'), (94, '94'), (95, '95'), (96, '96'), (97, '97'), (98, '98'), (99, '99')], null=True, validators=[django.core.validators.MinValueValidator(60.0), django.core.validators.MaxValueValidator(99.9)]),
        ),
    ]
