# Generated by Django 5.2 on 2025-06-16 16:48

import datetime
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profilcandidat_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilcandidat',
            name='date_de_naissance',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 16, 16, 48, 4, 872187, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='domaine_etude',
            field=models.CharField(choices=[('Administration', 'Administration'), ('Agronomie', 'Agronomie'), ('Agronomie générale', 'Agronomie générale'), ('Aménagement et gestion des ressources naturelles / Environnement', 'Aménagement et gestion des ressources naturelles / Environnement'), ('Anthropologie', 'Anthropologie'), ('Architecture', 'Architecture'), ('Arts dramatiques et cinématographie', 'Arts dramatiques et cinématographie'), ('Arts plastiques', 'Arts plastiques'), ('Aviation civile', 'Aviation civile'), ('Bâtiments et travaux publics', 'Bâtiments et travaux publics'), ('Biologie médicale', 'Biologie médicale'), ('Chimie', 'Chimie'), ('Cinéma', 'Cinéma'), ('Communication', 'Communication'), ('Comptabilité', 'Comptabilité'), ('Criminologie', 'Criminologie'), ('Design textile, stylisme et création de mode', 'Design textile, stylisme et création de mode'), ('Développement', 'Développement'), ('Diplôme MITEL', 'Diplôme MITEL'), ('Droit', 'Droit'), ('Écologie', 'Écologie'), ('Économie', 'Économie'), ('Électronique', 'Électronique'), ('Environnement et développement durable', 'Environnement et développement durable'), ('Exploitation Aéronautique', 'Exploitation Aéronautique'), ('Exploitation et production pétrolière', 'Exploitation et production pétrolière'), ('Finance, Banques et Assurances', 'Finance, Banques et Assurances'), ('Fiscalité', 'Fiscalité'), ('Foresterie', 'Foresterie'), ('Génie civil', 'Génie civil'), ('Génie des mines', 'Génie des mines'), ('Génie électrique', 'Génie électrique'), ('Génie informatique', 'Génie informatique'), ('Génie logiciel', 'Génie logiciel'), ('Génie mécanique', 'Génie mécanique'), ('Génie textile', 'Génie textile'), ('Géographie', 'Géographie'), ('Géologie', 'Géologie'), ('Géotechnique et Hydrogéologie', 'Géotechnique et Hydrogéologie'), ("Gestion de l'Environnement", "Gestion de l'Environnement"), ('Gestion financière', 'Gestion financière'), ('Gestion des entreprises et organisation du travail / GRH', 'Gestion des entreprises et organisation du travail / GRH'), ('Histoire et archivistique', 'Histoire et archivistique'), ('Hôtellerie et tourisme', 'Hôtellerie et tourisme'), ('Informatique', 'Informatique'), ('Kinésithérapie', 'Kinésithérapie'), ('Langues et littératures africaines', 'Langues et littératures africaines'), ('Langues étrangères (français, anglais, espagnol, chinois, allemand, etc.)', 'Langues étrangères (français, anglais, espagnol, chinois, allemand, etc.)'), ('Lettres et Sciences humaines', 'Lettres et Sciences humaines'), ('Management des organisations', 'Management des organisations'), ('Marketing', 'Marketing'), ('Mathématique', 'Mathématique'), ('Mathématique-Informatique', 'Mathématique-Informatique'), ('Médicine', 'Médicine'), ('Médecine générale', 'Médecine générale'), ('Médecine vétérinaire', 'Médecine vétérinaire'), ('Métallurgie', 'Métallurgie'), ('Musique', 'Musique'), ('Nutrition et technologie alimentaire', 'Nutrition et technologie alimentaire'), ('Odontologie (chirurgie dentaire)', 'Odontologie (chirurgie dentaire)'), ('Pêche et Aquaculture', 'Pêche et Aquaculture'), ('Philosophie', 'Philosophie'), ('Pharmacie', 'Pharmacie'), ('Photographie', 'Photographie'), ('Pédagogie', 'Pédagogie'), ('Physique', 'Physique'), ('Pétrole et gaz', 'Pétrole et gaz'), ('Psychologie', 'Psychologie'), ('Relations Internationales', 'Relations Internationales'), ('Réseau et Télécommunications', 'Réseau et Télécommunications'), ('Santé publique', 'Santé publique'), ('Sciences de la communication et journalisme', 'Sciences de la communication et journalisme'), ("Sciences de l'Éducation", "Sciences de l'Éducation"), ('Sciences infirmières', 'Sciences infirmières'), ('Sciences politiques et administratives', 'Sciences politiques et administratives'), ("Sciences et technologies de l'information", "Sciences et technologies de l'information"), ('Sociologie', 'Sociologie'), ('Statistique', 'Statistique'), ('Télécommunications', 'Télécommunications'), ('Théâtre', 'Théâtre'), ('Transport et logistique', 'Transport et logistique'), ('Urbanisme', 'Urbanisme'), ('Urbanisme et aménagement du territoire', 'Urbanisme et aménagement du territoire'), ('Zootechnie', 'Zootechnie'), ('Autre', 'Autre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='photo',
            field=models.FileField(blank=True, default='<function ProfilCandidat.user_photo_path at 0x000001C50602C720>/default.jpg', max_length=255, null=True, upload_to=users.models.ProfilCandidat.user_photo_path),
        ),
    ]
