# Generated by Django 5.2 on 2025-06-17 22:26

import datetime
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('candidat', 'Futur élève'), ('eleve', 'Elève'), ('alumni', 'Ancien élève'), ('evaluateur', 'Evaluateur'), ('correcteur', 'Correcteur'), ('formateur', 'Formateur'), ('agent', 'Agent administratif'), ('admin', 'Admin')], default='candidat', max_length=25),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='date_de_naissance',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 17, 22, 26, 39, 716181, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='photo',
            field=models.FileField(blank=True, default='<function ProfilCandidat.user_photo_path at 0x0000020BB0BBC720>/default.jpg', max_length=255, null=True, upload_to=users.models.ProfilCandidat.user_photo_path),
        ),
        migrations.AlterField(
            model_name='rolepromotionrequest',
            name='requested_role',
            field=models.CharField(choices=[('eleve', 'Elève'), ('alumni', 'Ancien élève'), ('evaluateur', 'Evaluateur'), ('correcteur', 'Correcteur'), ('formateur', 'Formateur'), ('agent', 'Agent administratif'), ('admin', 'Admin')], default='eleve', max_length=25),
        ),
    ]
