# Generated by Django 5.2 on 2025-06-22 18:10

import datetime
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionyear',
            old_name='debut',
            new_name='debut_session',
        ),
        migrations.RenameField(
            model_name='sessionyear',
            old_name='fin',
            new_name='fin_session',
        ),
        migrations.AddField(
            model_name='sessionyear',
            name='debut_soumission_candidature',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sessionyear',
            name='debut_soumission_recours',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sessionyear',
            name='fin_soumission_candidature',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sessionyear',
            name='fin_soumission_recours',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='date_de_naissance',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 22, 18, 10, 32, 795712, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profilcandidat',
            name='photo',
            field=models.FileField(blank=True, default='<function ProfilCandidat.user_photo_path at 0x00000207C3410220>/default.jpg', max_length=255, null=True, upload_to=users.models.ProfilCandidat.user_photo_path),
        ),
    ]
